# Generated by Django 3.0 on 2021-08-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_book_bk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bk_image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
